Geofeat to isochrone microservice
punkerpunker/geofeat pull request #3
Opened 2021-05-09 15:03 UTC by punkerpunker

I've decided to remove everything that is out of isochrones scope out of this project. Generally speaking, isochrones itself is a core functionality of `geofeat`, everything else was a burden. 

Seems like it is easier just to walk through the new branch in opposite to compare it with master because project became completely different.

2021-05-09 20:37 UTC, temsiPatrin approved these changes

2021-05-10 15:04 UTC, MTKarenin requested changes

2021-05-10 15:04 UTC, MTKarenin commented on containers/app/app.py
> +                subprocess.check_call([f'osmconvert {path} --drop-author --drop-version --out-osm -o={new_path}'], shell=True)
Again about the naming.
This name does not reveal what function do. User doesn't understand what is raw file and what is conwerted file.
I suggest: 
```suggestion
    @staticmethod
    def convert_pbf_to_osm(pbf_file_directory: str, osm_file_directory: str):
        for file in os.listdir(pbf_file_directory):
            if file.endswith(".osm.pbf"):
                path = os.path.join(pbf_file_directory, file)
                osm_name = file.rstrip('.pbf')
                new_path = os.path.join(osm_file_directory, osm_name)
                subprocess.check_call([f'osmconvert {path} --drop-author --drop-version --out-osm -o={new_path}'], shell=True)
```

2021-05-10 15:04 UTC, MTKarenin commented on containers/app/app.py
> +            os.makedirs(directory)
There is an inconsisency between function name and what it does. Accordin to it's name this function should create multiple directories, but it creates only one directory. I suggest to rename this function/
```suggestion
    @staticmethod
    def create_directory(path_to_directory: str):
        if not os.path.exists(path_to_directory):
            os.makedirs(path_to_directory)
```

2021-05-10 15:04 UTC, MTKarenin commented on containers/app/app.py
> +                                   f'--username postgres --password {password}'], shell=True)
And again - you don't realy understand what does this function load exactly
```suggestion
    @staticmethod
    def load_osm_files_to_db(osm_file_directory: str, mapconfig_path: str, password: str):
        for file in os.listdir(osm_file_directory):
            path = os.path.join(osm_file_directory, file)
            subprocess.check_call([f'osm2pgrouting --host pgrouting --f {path} --conf {mapconfig_path} --dbname postgres '
                                   f'--username postgres --password {password}'], shell=True)
```

2021-05-10 15:04 UTC, MTKarenin commented on containers/app/app.py
> +    Loader.load(CONVERTED_DIR, MAPCONFIG_PATH, DB_PASSWORD)
```suggestion
    Loader.create_directory(OSM_DIR)
    Loader.convert_pbf_to_osm(PBF_DIR, OSM_DIR)
    Loader.load_osm_files_to_db(OSM_DIR, MAPCONFIG_PATH, DB_PASSWORD)
```

2021-05-10 15:04 UTC, MTKarenin commented on containers/app/app.py
> +MAPCONFIG_PATH = '/osm/mapconfig.xml'
See comments below
```suggestion
PBF_DIR = '/osm/pbf'
OSM_DIR = '/osm/pbf/converted'
MAPCONFIG_PATH = '/osm/mapconfig.xml'
```

2021-05-10 15:29 UTC, AlexKay28 commented on containers/app/app.py
> +            os.makedirs(directory)
os.makedirs() method in Python is used to create a directory recursively. Actually, it looks good, but I agree that name should be more clear in terms of taken goal

2021-05-10 15:39 UTC, AlexKay28 commented on docker-compose.yaml
> +      - POSTGRES_PASSWORD=tttBBB777
maybe it would be right to change this pass to something else?)

2021-05-10 15:41 UTC, AlexKay28 approved these changes

2021-05-10 20:52 UTC, merged